In [1]:
import pandas as pd, datetime, glob, os
pd.options.display.float_format = '{:,.2f}'.format

In [2]:
csv_files = sorted(glob.glob(os.path.join("tefasbefas2files", "*.csv")))
dfs = {os.path.basename(f).split('.')[0]: pd.read_csv(f).fillna(0) for f in csv_files}

dag_files = ['tefas_dag_1','tefas_dag_2','tefas_dag_3']

t_dag_df = pd.concat([dfs[f] for f in dag_files], ignore_index=True)
t_fon_df = dfs['tefas_fon']
b_dag_df = dfs['befas_dag']
b_fon_df = dfs['befas_fon']
dfs. clear()

#dates = [pd.to_datetime(key, format='%d.%m.%Y') for key in b_dag_df['Tarih'].unique().tolist()]
dates = [i for i in b_dag_df['Tarih'].unique().tolist()]
t_dag_df.columns = [col[:-4] if col.endswith(' (%)') else col for col in t_dag_df.columns]
b_dag_df.columns = [col[:-4] if col.endswith(' (%)') else col for col in b_dag_df.columns]
assets = list(b_dag_df.iloc[0].index)[3:]

KeyError: 'tefas_dag_1'

In [3]:
columns_to_float = ['Fiyat','Tedavüldeki Pay Sayısı']
t_df = t_fon_df.merge(t_dag_df, on=['Tarih','Fon Kodu'], how='left', suffixes=('', '_drop'))
t_dag_df =  pd.DataFrame()
f_don_df = pd.DataFrame()
t_df = t_df.drop(columns=[col for col in t_df.columns if col.endswith('_drop')])
t_df[columns_to_float+assets] = (t_df[columns_to_float+assets]
                                    .replace(r"\.", "", regex=True)
                                    .replace(",", ".", regex=True)
                                    .astype(float))
b_df = b_fon_df.merge(b_dag_df, on=['Tarih','Fon Kodu'], how='left', suffixes=('', '_drop'))
b_dag_df =  pd.DataFrame()
b_don_df = pd.DataFrame()
b_df = b_df.drop(columns=[col for col in b_df.columns if col.endswith('_drop')])
b_df[columns_to_float+assets] = (b_df[columns_to_float+assets]
                                    .replace(r"\.", "", regex=True)
                                    .replace(",", ".", regex=True)
                                    .astype(float))

In [4]:
fundaums_t = pd.DataFrame(index=dates, columns=assets)
fundaums_b = pd.DataFrame(index=dates, columns=assets)
topfunds_t = {a:{} for a in assets}
topfunds_b = {a:{} for a in assets}

In [5]:
for day in dates:
    tday = t_df[t_df['Tarih']==day]
    bday = b_df[b_df['Tarih']==day]
    for s in assets:
        tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100 
        fundaums_t.loc[day,s] = tday.loc[:,s].sum()
        topfunds_t[s][day]= tday.loc[:,['Fon Kodu', s]].sort_values(s, ascending=False).head(5).reset_index(drop=True)
        bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
        fundaums_b.loc[day,s] = bday.loc[:,s].sum()
        topfunds_b[s][day]= bday.loc[:,['Fon Kodu', s]].sort_values(s, ascending=False).head(5).reset_index(drop=True)

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.

/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tday.loc[:,s] *= tday.loc[:,'Fiyat'] * tday.loc[:,'Tedavüldeki Pay Sayısı']/100
/var/folders/rf/gpy2j36s5qd53w_f572tfpzw0000gn/T/ipykernel_8101/3674681998.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bday.loc[:,s] *= bday.loc[:,'Fiyat'] * bday.loc[:,'Tedavüldeki Pay Sayısı']/100

In [6]:
fundaums = {s:fundaums_t.loc[:,s]+fundaums_b.loc[:,s] for s in assets}

In [16]:
fundaums

{'Hisse Senedi': 11.11.2024   616,464,902,989.93
 12.11.2024   621,422,759,787.27
 13.11.2024   616,295,780,387.06
 14.11.2024   623,025,304,896.01
 15.11.2024   627,623,048,191.40
                     ...
 03.02.2025   721,438,545,897.56
 04.02.2025   710,146,022,087.49
 05.02.2025   714,131,501,370.50
 06.02.2025   707,836,062,104.38
 07.02.2025   708,738,597,281.19
 Name: Hisse Senedi, Length: 64, dtype: object,
 'Devlet Tahvili': 11.11.2024   162,171,588,967.83
 12.11.2024   162,962,622,476.01
 13.11.2024   164,716,485,965.30
 14.11.2024   164,738,222,787.37
 15.11.2024   166,121,640,035.55
                     ...
 03.02.2025   425,531,585,618.40
 04.02.2025   429,082,497,873.76
 05.02.2025   429,740,214,036.87
 06.02.2025   431,938,013,306.35
 07.02.2025   430,026,697,227.55
 Name: Devlet Tahvili, Length: 64, dtype: object,
 'Hazine Bonosu': 11.11.2024       33,804,857.84
 12.11.2024       34,239,014.55
 13.11.2024       36,708,063.33
 14.11.2024       36,541,488.30
 15.11.2024       37,466,524.88
                     ...
 03.02.2025   15,364,661,362.67
 04.02.2025   15,723,323,731.87
 05.02.2025   15,826,612,875.72
 06.02.2025   15,975,621,730.27
 07.02.2025   16,026,383,767.20
 Name: Hazine Bonosu, Length: 64, dtype: object,
 'Döviz Kamu İç Borçlanma Araçları': 11.11.2024   29,876,474,074.63
 12.11.2024   29,588,710,360.05
 13.11.2024   31,502,517,680.96
 14.11.2024   31,783,903,503.03
 15.11.2024   31,996,955,812.00
                     ...
 03.02.2025   30,325,524,438.45
 04.02.2025   30,490,353,211.31
 05.02.2025   30,396,650,123.37
 06.02.2025   30,483,537,749.09
 07.02.2025   30,050,799,187.95
 Name: Döviz Kamu İç Borçlanma Araçları, Length: 64, dtype: object,
 'Finansman Bonosu': 11.11.2024   62,066,891,183.66
 12.11.2024   61,799,680,947.16
 13.11.2024   61,955,845,746.09
 14.11.2024   61,966,600,900.84
 15.11.2024   61,643,181,421.11
                     ...
 03.02.2025   68,102,204,787.92
 04.02.2025   68,202,792,455.14
 05.02.2025   70,382,621,708.74
 06.02.2025   70,866,956,459.97
 07.02.2025   72,411,314,709.86
 Name: Finansman Bonosu, Length: 64, dtype: object,
 'Özel Sektör Tahvili': 11.11.2024   57,453,773,450.85
 12.11.2024   57,512,485,268.37
 13.11.2024   57,215,803,421.40
 14.11.2024   57,576,004,709.01
 15.11.2024   59,638,220,629.75
                     ...
 03.02.2025   71,989,758,461.57
 04.02.2025   72,977,264,664.52
 05.02.2025   73,475,194,306.26
 06.02.2025   73,669,673,879.49
 07.02.2025   73,467,997,578.56
 Name: Özel Sektör Tahvili, Length: 64, dtype: object,
 'Varlığa Dayalı Menkul Kıymetler': 11.11.2024   2,769,693,113.96
 12.11.2024   2,785,894,708.37
 13.11.2024   2,779,136,374.57
 14.11.2024   2,990,129,305.44
 15.11.2024   2,948,716,917.00
                    ...
 03.02.2025   4,651,675,426.48
 04.02.2025   4,653,918,294.64
 05.02.2025   4,645,207,336.61
 06.02.2025   4,692,949,062.74
 07.02.2025   4,686,826,212.68
 Name: Varlığa Dayalı Menkul Kıymetler, Length: 64, dtype: object,
 'Kamu Dış Borçlanma Araçları': 11.11.2024   248,934,767,620.52
 12.11.2024   249,040,083,500.06
 13.11.2024   248,417,782,574.50
 14.11.2024   248,071,622,695.13
 15.11.2024   239,658,963,717.09
                     ...
 03.02.2025   270,358,761,254.02
 04.02.2025   272,043,781,157.09
 05.02.2025   277,390,488,254.31
 06.02.2025   255,208,144,916.97
 07.02.2025   251,986,942,917.82
 Name: Kamu Dış Borçlanma Araçları, Length: 64, dtype: object,
 'Özel Sektör Dış Borç. Araçları': 11.11.2024   526,407,378,291.74
 12.11.2024   526,741,689,051.62
 13.11.2024   523,790,482,903.05
 14.11.2024   522,249,532,501.68
 15.11.2024   525,587,309,276.98
                     ...
 03.02.2025   624,963,674,892.89
 04.02.2025   626,015,506,822.72
 05.02.2025   626,712,384,966.02
 06.02.2025   635,400,233,375.54
 07.02.2025   628,990,885,841.60
 Name: Özel Sektör Dış Borç. Araçları, Length: 64, dtype: object,
 'Takasbank Para Piyasası': 11.11.2024   47,206,334,483.78
 12.11.2024   39,457,585,069.50
 13.11.2024   41,633,229,917.78
 14.11.2024   46,181,765,235.93
 15.11.2024   46,214,723,653.10
                     ...
 03.02.2025   73,510,767,488.89
 04.02.2025   65,770,688,602.10
 05.02.2025   67,370,327,874.72
 06.02.2025   67,247,591,671.71
 07.02.2025   66,290,884,543.23
 Name: Takasbank Para Piyasası, Length: 64, dtype: object,
 'Kamu Kira Sertifikaları (TL)': 11.11.2024   32,990,218,329.50
 12.11.2024   32,974,747,311.02
 13.11.2024   33,230,159,893.54
 14.11.2024   33,813,135,398.15
 15.11.2024   33,835,407,572.66
                     ...
 03.02.2025   36,885,366,152.49
 04.02.2025   36,930,805,407.06
 05.02.2025   37,026,154,101.21
 06.02.2025   36,977,459,609.88
 07.02.2025   36,844,787,086.55
 Name: Kamu Kira Sertifikaları (TL), Length: 64, dtype: object,
 'Kamu Kira Sertifikaları (Döviz)': 11.11.2024   17,805,810,028.41
 12.11.2024   17,896,189,891.10
 13.11.2024   20,010,125,371.16
 14.11.2024   20,027,157,171.73
 15.11.2024   20,140,155,611.65
                     ...
 03.02.2025   16,838,811,399.51
 04.02.2025   16,721,298,591.06
 05.02.2025   16,646,792,979.14
 06.02.2025   16,616,496,012.44
 07.02.2025   16,579,427,495.33
 Name: Kamu Kira Sertifikaları (Döviz), Length: 64, dtype: object,
 'Özel Sektör Kira Sertifikaları': 11.11.2024   49,406,647,125.64
 12.11.2024   49,674,628,918.92
 13.11.2024   49,664,243,130.30
 14.11.2024   48,856,106,301.79
 15.11.2024   47,929,480,524.23
                     ...
 03.02.2025   58,562,974,052.35
 04.02.2025   58,868,877,529.12
 05.02.2025   58,491,446,700.58
 06.02.2025   58,603,745,979.13
 07.02.2025   59,847,297,610.75
 Name: Özel Sektör Kira Sertifikaları, Length: 64, dtype: object,
 'Kamu Yurt Dışı Kira Sertifikaları': 11.11.2024    6,727,068,871.89
 12.11.2024    8,035,244,680.59
 13.11.2024   10,819,096,429.70
 14.11.2024   10,649,327,167.00
 15.11.2024   10,981,871,238.15
                     ...
 03.02.2025   12,519,874,232.75
 04.02.2025   12,468,035,609.73
 05.02.2025   11,968,462,899.68
 06.02.2025   12,019,951,204.07
 07.02.2025   12,147,214,641.56
 Name: Kamu Yurt Dışı Kira Sertifikaları, Length: 64, dtype: object,
 'Ö.S. Yurt Dışı Kira Sertifikaları': 11.11.2024   9,092,820,128.79
 12.11.2024   8,953,100,173.09
 13.11.2024   6,727,340,549.41
 14.11.2024   6,725,003,569.39
 15.11.2024   6,710,130,212.46
                    ...
 03.02.2025   5,181,647,975.08
 04.02.2025   5,207,494,195.63
 05.02.2025   5,220,517,084.34
 06.02.2025   5,253,020,768.16
 07.02.2025   4,505,461,266.75
 Name: Ö.S. Yurt Dışı Kira Sertifikaları, Length: 64, dtype: object,
 'Mevduat (TL)': 11.11.2024   319,338,709,929.76
 12.11.2024   344,741,951,531.64
 13.11.2024   338,582,977,250.28
 14.11.2024   380,093,597,459.33
 15.11.2024   379,067,109,158.20
                     ...
 03.02.2025   494,593,941,099.45
 04.02.2025   518,617,741,829.39
 05.02.2025   511,778,873,188.59
 06.02.2025   500,610,885,173.54
 07.02.2025   516,245,399,065.65
 Name: Mevduat (TL), Length: 64, dtype: object,
 'Mevduat (Döviz)': 11.11.2024   107,105,173,725.89
 12.11.2024   107,395,857,936.91
 13.11.2024   110,029,736,904.54
 14.11.2024   111,623,989,954.76
 15.11.2024   111,153,698,629.77
                     ...
 03.02.2025   119,471,992,340.69
 04.02.2025   119,649,309,203.86
 05.02.2025   121,956,107,961.89
 06.02.2025   129,710,962,837.00
 07.02.2025   129,201,952,674.04
 Name: Mevduat (Döviz), Length: 64, dtype: object,
 'Katılma Hesabı (TL)': 11.11.2024    91,903,368,919.81
 12.11.2024   108,226,187,969.58
 13.11.2024   102,489,225,250.81
 14.11.2024   107,710,500,129.42
 15.11.2024   103,972,145,462.79
                     ...
 03.02.2025   123,504,184,721.19
 04.02.2025   154,696,016,554.67
 05.02.2025   153,234,827,605.80
 06.02.2025   154,758,654,694.85
 07.02.2025   159,173,963,861.83
 Name: Katılma Hesabı (TL), Length: 64, dtype: object,
 'Katılma Hesabı (Döviz)': 11.11.2024   120,141,557,137.73
 12.11.2024   122,470,522,911.31
 13.11.2024   123,546,232,932.16
 14.11.2024   121,975,648,614.31
 15.11.2024   121,773,456,855.21
                     ...
 03.02.2025   138,227,216,956.00
 04.02.2025   139,112,047,218.54
 05.02.2025   139,050,861,922.07
 06.02.2025   141,875,241,536.97
 07.02.2025   140,793,996,320.14
 Name: Katılma Hesabı (Döviz), Length: 64, dtype: object,
 'Katılma Hesabı (Altın)': 11.11.2024   701,976,529.87
 12.11.2024   688,918,291.62
 13.11.2024   693,784,293.98
 14.11.2024   673,452,926.01
 15.11.2024   672,220,936.34
                   ...
 03.02.2025   746,632,269.46
 04.02.2025   761,798,567.59
 05.02.2025   768,040,107.36
 06.02.2025   768,637,373.83
 07.02.2025   778,163,097.06
 Name: Katılma Hesabı (Altın), Length: 64, dtype: object,
 'Repo': 11.11.2024   -32,058,981,558.24
 12.11.2024   -30,149,530,447.60
 13.11.2024   -28,422,157,335.28
 14.11.2024   -30,961,220,487.18
 15.11.2024   -28,928,552,777.44
                     ...
 03.02.2025   -39,637,121,698.03
 04.02.2025   -39,428,304,523.23
 05.02.2025   -39,087,049,675.82
 06.02.2025   -40,405,074,104.35
 07.02.2025   -39,010,447,098.29
 Name: Repo, Length: 64, dtype: object,
 'Ters-Repo': 11.11.2024   1,362,990,365,747.41
 12.11.2024   1,353,925,167,614.17
 13.11.2024   1,367,294,369,350.80
 14.11.2024   1,331,132,336,893.95
 15.11.2024   1,332,186,406,355.25
                      ...
 03.02.2025   1,479,061,987,507.05
 04.02.2025   1,478,009,591,925.10
 05.02.2025   1,479,672,876,665.11
 06.02.2025   1,475,214,445,730.08
 07.02.2025   1,461,422,562,725.66
 Name: Ters-Repo, Length: 64, dtype: object,
 'Kıymetli Madenler': 11.11.2024    73,959,300,478.07
 12.11.2024    72,655,978,781.43
 13.11.2024    75,329,688,419.11
 14.11.2024    72,805,203,099.10
 15.11.2024    72,283,695,351.86
                     ...
 03.02.2025   100,121,132,866.69
 04.02.2025   100,288,887,455.64
 05.02.2025   101,865,477,699.38
 06.02.2025    97,855,301,361.07
 07.02.2025    98,584,139,300.05
 Name: Kıymetli Madenler, Length: 64, dtype: object,
 'Kıymetli Madenler Cinsinden BYF': 11.11.2024   47,620,372,706.61
 12.11.2024   46,483,259,083.27
 13.11.2024   46,154,989,156.07
 14.11.2024   45,926,848,340.91
 15.11.2024   45,498,570,991.84
                     ...
 03.02.2025   38,797,565,574.46
 04.02.2025   39,268,050,970.14
 05.02.2025   39,216,081,484.80
 06.02.2025   39,507,338,693.84
 07.02.2025   39,531,352,730.45
 Name: Kıymetli Madenler Cinsinden BYF, Length: 64, dtype: object,
 'Kıymetli Madenler Kamu B. A.': 11.11.2024   39,559,154,681.50
 12.11.2024   38,797,514,946.93
 13.11.2024   39,342,599,941.80
 14.11.2024   39,120,404,335.00
 15.11.2024   38,840,918,945.96
                     ...
 03.02.2025   42,125,580,837.31
 04.02.2025   42,246,789,468.21
 05.02.2025   42,865,933,208.70
 06.02.2025   43,543,485,241.70
 07.02.2025   43,460,926,205.43
 Name: Kıymetli Madenler Kamu B. A., Length: 64, dtype: object,
 'Kıymetli Madenler Kamu Kira Sertifika.': 11.11.2024   244,223,672,517.82
 12.11.2024   239,790,769,098.53
 13.11.2024   241,896,801,876.18
 14.11.2024   238,299,564,051.43
 15.11.2024   240,983,567,959.03
                     ...
 03.02.2025   322,470,843,178.21
 04.02.2025   322,235,472,117.36
 05.02.2025   324,733,551,057.63
 06.02.2025   335,816,708,366.07
 07.02.2025   326,705,088,398.45
 Name: Kıymetli Madenler Kamu Kira Sertifika., Length: 64, dtype: object,
 'Yabancı Kamu Borçlanma Araçları': 11.11.2024   66,977,875,130.45
 12.11.2024   67,195,510,575.52
 13.11.2024   67,039,683,570.28
 14.11.2024   66,602,613,299.67
 15.11.2024   67,866,606,575.07
                     ...
 03.02.2025   31,979,836,419.86
 04.02.2025   32,148,954,589.35
 05.02.2025   31,677,206,238.55
 06.02.2025   32,834,607,729.46
 07.02.2025   31,968,801,738.57
 Name: Yabancı Kamu Borçlanma Araçları, Length: 64, dtype: object,
 'Yabancı Özel Sektör B.A.': 11.11.2024   20,950,403,566.79
 12.11.2024   20,853,328,359.70
 13.11.2024   20,789,520,167.63
 14.11.2024   20,719,921,375.85
 15.11.2024   20,830,119,057.29
                     ...
 03.02.2025   17,759,645,460.74
 04.02.2025   17,800,903,250.16
 05.02.2025   17,785,984,112.19
 06.02.2025   17,792,903,901.54
 07.02.2025   17,623,238,111.55
 Name: Yabancı Özel Sektör B.A., Length: 64, dtype: object,
 'Yabancı Hisse Senedi': 11.11.2024   87,297,703,596.11
 12.11.2024   87,517,240,586.05
 13.11.2024   87,581,760,012.97
 14.11.2024   87,224,582,961.06
 15.11.2024   86,890,117,096.04
                     ...
 03.02.2025   87,012,677,294.37
 04.02.2025   84,541,905,322.25
 05.02.2025   85,568,396,385.06
 06.02.2025   86,373,009,724.06
 07.02.2025   86,046,890,501.00
 Name: Yabancı Hisse Senedi, Length: 64, dtype: object,
 'Yabancı Borsa Yatırım Fonları': 11.11.2024   39,653,101,076.97
 12.11.2024   39,341,361,298.56
 13.11.2024   39,034,599,167.41
 14.11.2024   34,065,816,542.33
 15.11.2024   38,939,097,004.92
                     ...
 03.02.2025   35,782,489,201.58
 04.02.2025   35,611,590,478.32
 05.02.2025   36,036,809,207.89
 06.02.2025   36,391,456,621.37
 07.02.2025   36,550,918,757.29
 Name: Yabancı Borsa Yatırım Fonları, Length: 64, dtype: object,
 'Yatırım Fonları Katılma Payları': 11.11.2024   188,369,759,270.21
 12.11.2024   186,888,956,493.61
 13.11.2024   189,796,535,272.13
 14.11.2024   176,504,548,418.87
 15.11.2024   188,351,601,316.63
                     ...
 03.02.2025   193,716,154,647.00
 04.02.2025   192,571,739,413.22
 05.02.2025   191,375,840,906.41
 06.02.2025   193,330,060,200.26
 07.02.2025   192,188,458,144.73
 Name: Yatırım Fonları Katılma Payları, Length: 64, dtype: object,
 'BYF Katılma Payları': 11.11.2024   39,405,720,391.31
 12.11.2024   39,428,087,430.37
 13.11.2024   39,144,900,733.08
 14.11.2024   38,526,089,100.51
 15.11.2024   39,115,631,383.94
                     ...
 03.02.2025   36,248,917,737.74
 04.02.2025   36,077,873,797.06
 05.02.2025   36,533,763,549.86
 06.02.2025   36,410,367,536.99
 07.02.2025   36,563,702,083.92
 Name: BYF Katılma Payları, Length: 64, dtype: object,
 'Gayrimenkul Yatırım Fon Katılma Payları': 11.11.2024   7,426,105,526.95
 12.11.2024   7,414,500,475.35
 13.11.2024   7,438,572,076.38
 14.11.2024   7,467,441,788.05
 15.11.2024   7,458,391,195.70
                    ...
 03.02.2025   9,685,842,696.59
 04.02.2025   9,720,788,673.66
 05.02.2025   9,718,932,501.13
 06.02.2025   9,708,425,598.70
 07.02.2025   9,733,271,954.68
 Name: Gayrimenkul Yatırım Fon Katılma Payları, Length: 64, dtype: object,
 'Girişim S. Yatırım Fon Katılma Payları': 11.11.2024   27,202,398,989.02
 12.11.2024   27,258,454,195.77
 13.11.2024   27,284,179,488.99
 14.11.2024   27,171,622,681.92
 15.11.2024   27,202,716,314.25
                     ...
 03.02.2025   30,047,702,576.89
 04.02.2025   30,071,395,477.84
 05.02.2025   30,090,872,948.80
 06.02.2025   30,230,082,924.32
 07.02.2025   30,133,235,862.98
 Name: Girişim S. Yatırım Fon Katılma Payları, Length: 64, dtype: object,
 'Vadeli İşlemler Nakit Teminatları': 11.11.2024   33,018,961,406.49
 12.11.2024   32,785,262,887.93
 13.11.2024   32,973,749,670.92
 14.11.2024   32,829,225,032.03
 15.11.2024   33,248,380,849.63
                     ...
 03.02.2025   35,704,897,786.79
 04.02.2025   35,609,638,835.45
 05.02.2025   36,173,640,220.14
 06.02.2025   36,986,244,602.51
 07.02.2025   35,817,046,060.80
 Name: Vadeli İşlemler Nakit Teminatları, Length: 64, dtype: object,
 'Diğer': 11.11.2024   100,289,462,509.11
 12.11.2024    85,406,837,005.77
 13.11.2024    87,917,583,038.78
 14.11.2024    85,407,337,975.73
 15.11.2024    91,082,004,650.31
                     ...
 03.02.2025   121,685,255,188.05
 04.02.2025    95,886,019,803.04
 05.02.2025    94,335,365,629.97
 06.02.2025    94,056,253,623.84
 07.02.2025    91,021,308,178.65
 Name: Diğer, Length: 64, dtype: object}

In [18]:
fundaums[assets[1]].tail(30)

27.12.2024   242,114,651,174.67
30.12.2024   243,398,800,966.44
31.12.2024   243,848,386,346.13
02.01.2025   245,066,586,346.55
03.01.2025   245,486,153,422.62
06.01.2025   249,682,519,703.05
07.01.2025   253,638,844,657.95
08.01.2025   256,448,074,931.04
09.01.2025   259,546,609,076.98
10.01.2025   265,254,235,376.88
13.01.2025   271,047,353,318.10
14.01.2025   274,291,890,846.77
15.01.2025   312,927,938,800.15
16.01.2025   329,414,465,984.34
17.01.2025   335,884,598,480.40
20.01.2025   342,474,766,686.38
21.01.2025   346,694,983,663.87
22.01.2025   356,854,119,494.26
23.01.2025   368,408,765,372.08
24.01.2025   375,759,085,864.13
27.01.2025   323,325,883,138.98
28.01.2025   394,932,063,319.29
29.01.2025   401,030,323,642.70
30.01.2025   410,869,360,982.11
31.01.2025   418,189,337,982.52
03.02.2025   425,531,585,618.40
04.02.2025   429,082,497,873.76
05.02.2025   429,740,214,036.87
06.02.2025   431,938,013,306.35
07.02.2025   430,026,697,227.55
Name: Devlet Tahvili, dtype: object

In [8]:
def concat5(df1, df2, s):
    newdf = pd.concat([df1,df2])
    newdf = newdf.sort_values(s,ascending=False).head(5).reset_index(drop=True)
    return newdf

In [9]:
topfunds = {a:{} for a in assets}
for day in dates:
    for a in assets:
        topfunds[a][day] = concat5(topfunds_t[a][day],topfunds_b[a][day], a)

In [10]:
topfunds_b[assets[1]]['07.02.2025']

  Fon Kodu    Devlet Tahvili
0      VEI 15,171,007,825.76
1      AET 15,141,627,864.53
2      AEI 13,942,994,696.92
3      AMF 10,021,945,391.86
4      AZL  9,958,598,558.59

In [11]:
topfunds_t[assets[0]]['07.02.2025']

  Fon Kodu      Hisse Senedi
0      YAS 10,814,711,135.11
1      URV  8,405,914,821.20
2      IPE  7,699,007,686.06
3      TI2  7,116,049,941.30
4      ZJB  7,112,686,924.38

In [12]:
topfunds_b[assets[0]]['07.02.2025']

  Fon Kodu      Hisse Senedi
0      AZH 29,372,305,112.91
1      AH5 20,067,786,853.28
2      AEH 19,879,256,780.70
3      GEH 14,071,051,139.93
4      VEI 10,276,358,451.93

In [15]:
assets

['Hisse Senedi',
 'Devlet Tahvili',
 'Hazine Bonosu',
 'Döviz Kamu İç Borçlanma Araçları',
 'Finansman Bonosu',
 'Özel Sektör Tahvili',
 'Varlığa Dayalı Menkul Kıymetler',
 'Kamu Dış Borçlanma Araçları',
 'Özel Sektör Dış Borç. Araçları',
 'Takasbank Para Piyasası',
 'Kamu Kira Sertifikaları (TL)',
 'Kamu Kira Sertifikaları (Döviz)',
 'Özel Sektör Kira Sertifikaları',
 'Kamu Yurt Dışı Kira Sertifikaları',
 'Ö.S. Yurt Dışı Kira Sertifikaları',
 'Mevduat (TL)',
 'Mevduat (Döviz)',
 'Katılma Hesabı (TL)',
 'Katılma Hesabı (Döviz)',
 'Katılma Hesabı (Altın)',
 'Repo',
 'Ters-Repo',
 'Kıymetli Madenler',
 'Kıymetli Madenler Cinsinden BYF',
 'Kıymetli Madenler Kamu B. A.',
 'Kıymetli Madenler Kamu Kira Sertifika.',
 'Yabancı Kamu Borçlanma Araçları',
 'Yabancı Özel Sektör B.A.',
 'Yabancı Hisse Senedi',
 'Yabancı Borsa Yatırım Fonları',
 'Yatırım Fonları Katılma Payları',
 'BYF Katılma Payları',
 'Gayrimenkul Yatırım Fon Katılma Payları',
 'Girişim S. Yatırım Fon Katılma Payları',
 'Vadeli İşlemler Nakit Teminatları',
 'Diğer']